---

- name: Launch EC2 Instance
  local_action:
    module: ec2
    keypair: "{{ keypair }}"
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
    wait: true
    region: "{{ region }}"
    instance_tags: "{{instance_tags}}"
    volumes:
      - device_name: /dev/sda1
        volume_size: "{{ root_ebs_size }}"
    zone: "{{ zone }}"
  register: ec2
