---

- name: Install Requirement
  pip:
    name: gunicorn
    virtualenv: "{{ venv_home }}"
    state: present
  

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=django-imager.conf.j2 dest=/etc/init/django-imager.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=django-imager state=restarted
