---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=djang_imager.conf.j2 dest=/etc/init/django_imager.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=django_imager state=restarted
