---

- name: Get DB Password
  include_vars: secrets.yml

- name: Create RDS instance
  local_action:
    module: rds
    command: create
    db_engine: postgres
    db_name: imagerDB
    instance_name: imager
    instance_type: db.t2.micro
    license_model: postgresql-license
    vpc_security_groups: sg-2edc0d57
    zone: us-west-2b
    region: us-west-2
    size: 5
    username: imageruser
    password: "{{ db_password }}"
